site_name: Theory of everything
#site_url: https://howallworks.github.io/theoryofeverything/

theme:
    name: 'material'
    language: en
    features:
        - navigation.instant
    palette:

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
        
extra:
  alternate:
    - name: English
      link: /theoryofeverything/theoryofeverything/ 
      lang: en
    - name: Русский
      link: /theoryofeverything/ru/theoryofeverything/
      lang: ru
    
    

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search:
      lang: en
      #lang: 
        #- en
        #- ru
  - roamlinks 
  - mermaid2
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
          site_name: Theory of everything
        ru:
          name: Русский
          build: true
          site_name: Теория всего
      nav_translations:
        en:
          Theoryofeverything: Theory of everything
          theoryofeverythingPracticalC: Theory of everything. Practical Consequences
          Home: Foreword
          Index: Foreword
          README: Foreword
          ElementaryParticles: Elementary particles
          ParticlesOfStandardModel: Particles of Standard Model
          TermsOrAbbreviations: Terms or abbreviations 
        ru:
          Theoryofeverything: Теория всего
          theoryofeverythingPracticalC: Теория всего. Практические последствия
          Home: Предисловие
          Index: Предисловие
          README: Предисловие
          ElementaryParticles: Элементарные частицы
          ParticlesOfStandardModel: Частицы Стандартной модели
          TermsOrAbbreviations: Термины или сокращения 
          Quantum graviton: Квант гравитон 
          Quantum photon: Квант фотон 
          Photon: Фотон 
          Accretion disk: Аккрецио́нный диск 
          Albert Einstein: Альбе́рт Эйнште́йн 
          Blazar: Блаза́р 
          Elementary particle: Элементарная частица 
          GTR: ОТО 
          Helicity: Спиральность 
          Relativistic jet: Релятиви́стская струя 
          SMBH: СМЧД 
          Standard Model: Стандартная модель 
          Blandford–Znajek process: Процесс Блэнфорда — Знаека 
          Penrose process: процесс Пенроуза 
          Hafele–Keating experiment: Эксперимент Хафеле — Китинга 
          
extra_javascript:
  #- javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
