site_name: Theory of everything

theme:
    name: 'material'
    language: en
    features:
        - navigation.instant
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
extra:
  alternate:
    - name: English
      link: /theoryofeverything/en/ 
      lang: en
    - name: Русский
      link: /theoryofeverything/ru/
      lang: ru

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search:
      lang: 
        - en
        - ru
  - roamlinks 
  - mermaid2
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
          site_name: Theory of everything
        ru:
          name: Русский
          build: true
          site_name: Теория всего
      nav_translations:
        en:
          Index: Theory of everything
          ElementaryParticles: Elementary particles
          ParticlesOfStandardModel: Particles of Standard Model
          TermsOrAbbreviations: Terms or abbreviations 
        ru:
          Index: Теория всего
          ElementaryParticles: Элементарные частицы
          ParticlesOfStandardModel: Частицы Стандартной модели
          TermsOrAbbreviations: Термины или сокращения 
          Quantum graviton: Квант гравитон 
          Quantum photon: Квант фотон 
          GTR: ОТО 
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
